#!/bin/bash
    userlist="$(cut -d ":" -f1 /etc/passwd)"
    found=0
    read -p "Enter your username (lower_case): " username
    for j in $userlist; do
        if [[ "$username" = "$j" ]]; then
            found=1
            break
        else
            continue
        fi
    done
    if [ "$found" -eq 1 ]; then
        echo -e "user found: \"$username\""

    else
        echo -"no user \"$username\""
        while true; do
            read -p "try again (Y/n)? " yn
            case $yn in
                [Nn])
                    exit 0
                ;;
                [Yy]|"")
                    break
                ;;
            esac
        done
    fi
    
printf "Installing packages........\n"
sudo xbps-install xorg-minimal xterm git cabal-install dunst feh ghc libX11-devel libXft-devel libXinerama-devel libXrandr-devel libXScrnSaver-devel pkg-config dmenu slock st trayer-srg ncurses-devel xmobar gmrun redshift rofi udiskie xautolock xf86-input-synaptics xcompmgr 

printf "Install Cabal........\n"
cabal update

printf "Install XMonad........\n"
cabal install --lib xmonad xmonad-contrib X11
cabal install xmonad

printf "Adding Cabal's BIN dir to PATH......\n"
echo "export PATH="$HOME/.cabal/bin:$PATH"" >> ~/.bashrc
source ~/.bashrc

printf "XMonad session........\n"
sudo mkdir -p /usr/share/xsessions
sudo tee /usr/share/xsessions/xmonad.desktop > /dev/null << EOF
[Desktop Entry]
Name=XMonad
Comment=Lightweight tiling window manager
Exec=dbus-launch /home/$username/.local/bin/xmonad
Type=Application
EOF

printf "XMonad configs........\n"
cp -r xmonad/ ~/.config/
cp -r xmobar/ ~/.config/
cp -r Wallpaper/ ~/
cp -r ../common/rofi_c/rofi/ ~/.config/
cp -r ../common/config/dunst/ ~/.config/
