#!/usr/bin/env bash

SCRIPTPATH="$( cd "$(dirname "$0")" || return ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --no-fehbg --bg-fill "$SCRIPTPATH"/down.jpg
fi

leftwm-command UnloadTheme

pkill polybar &
pkill xcompmgr &
pkill dunst &
pkill redshift-gtk &
pkill nm-applet &
pkill volumeicon &
pkill octoxbps-notifier &
pkill udiskie &
pkill xautolock &
pkill cabtticon &
