# Application Launchers
bind=SUPER,space,spawn,noctalia ipc launcher toggle
bind=SUPER,comma,spawn,noctalia ipc settings toggle
bind=SUPER,n,spawn,noctalia ipc notifications toggleHistory
bind=SUPER+SHIFT,n,spawn,noctalia ipc calendar toggle
bind=SUPER,x,spawn,noctalia ipc sessionMenu toggle
bind=SUPER,y,spawn,noctalia ipc wallpaper toggle

# Terminal
bind=SUPER,t,spawn,kitty

# Exit
bind=ALT,m,quit
bind=SUPER,q,killclient,

# Security
bind=SUPER+ALT,l,spawn,noctalia ipc lockScreen lock

# Audio Controls
bind=NONE,XF86AudioRaiseVolume,spawn,noctalia ipc volume increase 3
bind=NONE,XF86AudioLowerVolume,spawn,noctalia ipc volumedecrease 3
bind=NONE,XF86AudioMute,spawn,noctalia ipc volume muteOutput

# Brightness Controls
bind=NONE,XF86MonBrightnessUp,spawn,noctalia ipc brightness increase 5
bind=NONE,XF86MonBrightnessDown,spawn,noctalia ipc brightness decrease 5
