#!/bin/env bash

SELECTION=$(echo -e "suspend\nlogout\nreboot\nshutdown" | fuzzel -d -p " " -w 15 -l 4)

reboot_confirm() {
	SELECTION=$(echo -e "confirm reboot\ncancel reboot" | fuzzel -d -p " " -w 15 -l 2)
	case $SELCTION in
		"confirm reboot")
			reboot
			;;
		*)
			;;
	esac
}
shutdown_confirm() {
		SELECTION=$(echo -e "confirm shutdown\ncancel shutdown" | fuzzel -d -p " " -w 15 -l 2)
		case $SELCTION in
			"confirm shutdown")
				shutdown
				;;
			*)
				;;
		esac
}

case $SELECTION in
	"suspend")
		loginctl suspend
		;;
	"logout")
		loginctl terminate-user $USER
		;;
	"reboot")
		loginctl reboot
		;;
	"shutdown")
		loginctl poweroff
		;;
	*)
		;;
esac
